### ISSUE TITLE
Bundle CSS with components by default (and provide alternative sans-CSS bundle)

### ISSUE THREAD

**Issue by joshuef** [sociomantic-tsunami/nessie-ui#82]
## Currently

Only one giiiaaaant js/css file is exported. Which means if you're importing only one or two components, you get _A LOT_ of cruft. 

## Wanted

Are we able to generate sub releases for each component? (js and css).

-----

I wonder if tree shaking solves this (at least the JS side). But I don't think that'll work for CSS.

**Comment by conor-cafferkey-sociomantic** [comment]
Hey @joshuef! On the JS side tree shaking _should_ solve it. Regarding the CSS: it will need to be bundled with the JS for that to work. This is how it should be of course (the only reason it’s a separate file is for Sociomantic legacy reasons).

So, I think the action point for this issue is that the default bundle should have the CSS baked in to the JS. And to provide an alternative bundle with JS and CSS separated.

**Comment by joshuef** [comment]
Sounds legit to me. I'll verify tree shakiness asap. (I think we already have a bundle w/o exporting the CSS for lochness, or? It's been a while, I don't remember.... Anyway, shouldn't be that big a thing anyway).

**Comment by conor-cafferkey-sociomantic** [comment]
Closed by https://github.com/sociomantic-tsunami/nessie-ui/pull/609
