### ISSUE TITLE
[ComboBox] Display multiselect as tag input

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#869]
### Wanted

When `isMultiselect` is `true`, currently selected options should be shown as tags, similar to TagInput component.

**Comment by daniel-martic-sociomantic** [comment]
This is a bit tricky to pull off: at the moment, this component is composed of `TextInputWithIcon` that breaks when we try to show multiple selected options using `Tag` component for each; this is because we're passing either selected option as a string to `value` of `<input>`, or a string `X items selected`.

It seems like a bad idea to try and "imitate" behaviour of `Tag` (combining re-usage of `Tag` styles/structure/functionality), instead of just using the actual `Tag`.
Also, we're planning to [remove `TextInputWithIcon`](https://github.com/sociomantic-tsunami/nessie-ui/issues/760) as a component and replace it with more modular approach.

To achieve this, I think the best approach (at the moment) would be to remove `TextInputWithIcon` from `ComboBox` and reconstruct `ComboBox` to work like a mix between `TextInputWithIcon` and `TagInput` => input that contains `Tags` (`isMultiselect`), `TextInput` (also needed when `isSearchable`) and `IconButton`.
